export const Products = [
  {
    id: "TP001",
    name: "UltraSlim Pro Laptop",
    price: 1299.99,
    rating: 5,
    description: "Powerful and lightweight laptop with 16GB RAM and 512GB SSD",
    inStock: 0,
    fastDelivery: true,
    image: "https://picsum.photos/300/200?random=1",
  },
  {
    id: "TP002",
    name: "SmartHome Hub",
    price: 149.99,
    rating: 4,
    description: "Central control unit for all your smart home devices",
    inStock: 6,
    fastDelivery: false,
    image: "https://picsum.photos/300/200?random=2",
  },
  {
    id: "TP003",
    name: "NoiseCancel Pro Headphones",
    price: 299.99,
    rating: 5,
    description:
      "Over-ear headphones with advanced noise cancellation technology",
    inStock: 2,
    fastDelivery: true,
    image: "https://picsum.photos/300/200?random=3",
  },
  {
    id: "TP004",
    name: "4K UltraHD Smart TV",
    price: 799.99,
    rating: 4,
    description: "55-inch 4K smart TV with HDR and built-in streaming apps",
    inStock: 31,
    fastDelivery: false,
    image: "https://picsum.photos/300/200?random=4",
  },
  {
    id: "TP005",
    name: "PowerBank 20000mAh",
    price: 49.99,
    rating: 4,
    description: "High-capacity portable charger with fast charging capability",
    inStock: 0,
    fastDelivery: true,
    image: "https://picsum.photos/300/200?random=5",
  },
  {
    id: "TP006",
    name: "Gaming Mouse RGB",
    price: 79.99,
    rating: 5,
    description: "High-precision gaming mouse with customizable RGB lighting",
    inStock: 1,
    fastDelivery: true,
    image: "https://picsum.photos/300/200?random=6",
  },
  {
    id: "TP007",
    name: "Wireless Earbuds Pro",
    price: 159.99,
    rating: 4,
    description: "True wireless earbuds with active noise cancellation",
    inStock: 6,
    fastDelivery: true,
    image: "https://picsum.photos/300/200?random=7",
  },
  {
    id: "TP008",
    name: "Smart Fitness Watch",
    price: 199.99,
    rating: 4,
    description: "Advanced fitness tracker with heart rate and GPS",
    inStock: 6,
    fastDelivery: false,
    image: "https://picsum.photos/300/200?random=8",
  },
  {
    id: "TP009",
    name: "Portable SSD 1TB",
    price: 129.99,
    rating: 5,
    description: "Fast and compact external SSD with 1TB storage",
    inStock: 0,
    fastDelivery: true,
    image: "https://picsum.photos/300/200?random=9",
  },
  {
    id: "TP010",
    name: "4K Webcam",
    price: 129.99,
    rating: 4,
    description: "High-quality 4K webcam for streaming and video conferencing",
    inStock: 2,
    fastDelivery: false,
    image: "https://picsum.photos/300/200?random=10",
  },
  {
    id: "TP011",
    name: "Mesh WiFi System",
    price: 249.99,
    rating: 5,
    description: "Whole-home mesh WiFi system for seamless coverage",
    inStock: 4,
    fastDelivery: true,
    image: "https://picsum.photos/300/200?random=11",
  },
  {
    id: "TP012",
    name: "Curved Gaming Monitor",
    price: 399.99,
    rating: 4,
    description: "34-inch curved gaming monitor with high refresh rate",
    inStock: 0,
    fastDelivery: false,
    image: "https://picsum.photos/300/200?random=12",
  },
  {
    id: "TP013",
    name: "Mechanical Keyboard",
    price: 129.99,
    rating: 5,
    description: "RGB mechanical keyboard with customizable switches",
    inStock: 0,
    fastDelivery: true,
    image: "https://picsum.photos/300/200?random=13",
  },
  {
    id: "TP014",
    name: "Smart Doorbell",
    price: 179.99,
    rating: 4,
    description: "WiFi-enabled doorbell with HD camera and two-way audio",
    inStock: 6,
    fastDelivery: false,
    image: "https://picsum.photos/300/200?random=14",
  },
  {
    id: "TP015",
    name: "Portable Projector",
    price: 299.99,
    rating: 4,
    description: "Compact HD projector with built-in battery",
    inStock: 4,
    fastDelivery: true,
    image: "https://picsum.photos/300/200?random=15",
  },
  {
    id: "TP016",
    name: "Wireless Charging Pad",
    price: 39.99,
    rating: 4,
    description: "Fast wireless charging pad for Qi-compatible devices",
    inStock: 1,
    fastDelivery: true,
    image: "https://picsum.photos/300/200?random=16",
  },
  {
    id: "TP017",
    name: "Smart Thermostat",
    price: 199.99,
    rating: 5,
    description: "WiFi-enabled smart thermostat with energy-saving features",
    inStock: 1,
    fastDelivery: false,
    image: "https://picsum.photos/300/200?random=17",
  },
  {
    id: "TP018",
    name: "Bluetooth Speaker",
    price: 89.99,
    rating: 4,
    description:
      "Portable waterproof Bluetooth speaker with 20-hour battery life",
    inStock: 1,
    fastDelivery: true,
    image: "https://picsum.photos/300/200?random=18",
  },
  {
    id: "TP019",
    name: "VR Headset",
    price: 399.99,
    rating: 4,
    description:
      "High-resolution virtual reality headset with motion controllers",
    inStock: 0,
    fastDelivery: false,
    image: "https://picsum.photos/300/200?random=19",
  },
  {
    id: "TP020",
    name: "Smart Light Bulbs",
    price: 79.99,
    rating: 4,
    description: "Set of 4 WiFi-enabled color-changing smart bulbs",
    inStock: 1,
    fastDelivery: true,
    image: "https://picsum.photos/300/200?random=20",
  },
  {
    id: "TP021",
    name: "Robotic Vacuum",
    price: 299.99,
    rating: 4,
    description: "Smart robot vacuum with mapping and app control",
    inStock: 4,
    fastDelivery: false,
    image: "https://picsum.photos/300/200?random=21",
  },
  {
    id: "TP022",
    name: "Noise-Cancelling Earbuds",
    price: 199.99,
    rating: 5,
    description: "True wireless earbuds with adaptive noise cancellation",
    inStock: 8,
    fastDelivery: true,
    image: "https://picsum.photos/300/200?random=22",
  },
  {
    id: "TP023",
    name: "Portable Charger",
    price: 29.99,
    rating: 4,
    description: "Slim 10000mAh power bank with fast charging",
    inStock: 2,
    fastDelivery: true,
    image: "https://picsum.photos/300/200?random=23",
  },
  {
    id: "TP024",
    name: "Smart Scale",
    price: 59.99,
    rating: 4,
    description: "WiFi-connected scale with body composition analysis",
    inStock: 9,
    fastDelivery: false,
    image: "https://picsum.photos/300/200?random=24",
  },
  {
    id: "TP025",
    name: "Wireless Gaming Headset",
    price: 149.99,
    rating: 5,
    description: "Low-latency wireless gaming headset with surround sound",
    inStock: 5,
    fastDelivery: true,
    image: "https://picsum.photos/300/200?random=25",
  },
];
